CREATE TABLE T_CUSTOMERS
(
  IdCustomer INT NOT NULL,
  FirstName VARCHAR2(20) NOT NULL,
  LastName VARCHAR2(40) NOT NULL,
  
  CONSTRAINT PK_CUSTOMER PRIMARY KEY(IdCustomer)
)
TABLESPACE BOOKSTOREBIG;

CREATE TABLE T_GENRES
(
  IdGenre INT NOT NULL,
  Genre VARCHAR2(20) NOT NULL,
  
  CONSTRAINT PK_GENRE PRIMARY KEY(IdGenre),
  CONSTRAINT UQ_GENRE UNIQUE(Genre)
)
TABLESPACE BOOKSTOREBIG;

CREATE TABLE T_CUSTOMERS_GENRES
(
  IdCustomer INT NOT NULL,
  IdGenre INT NOT NULL,
  
  CONSTRAINT PK_CUSTOMER_GENRE PRIMARY KEY (IdCustomer, IdGenre),
  CONSTRAINT FK_CUSTOMER FOREIGN KEY (IdCustomer) 
    REFERENCES T_CUSTOMERS(IdCustomer)
    ON DELETE CASCADE,
  CONSTRAINT FK_GENRE FOREIGN KEY (IdGenre)
    REFERENCES T_GENRES(IdGenre)
    ON DELETE CASCADE
)
TABLESPACE BOOKSTOREBIG;

CREATE SEQUENCE sqCustomers
START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 99;

create or replace
PROCEDURE NEW_CUSTOMER
  (v_FirstName IN T_CUSTOMERS.FirstName%TYPE, v_LastName IN T_CUSTOMERS.CSurname%TYPE,
   v_IdCustomer OUT T_CUSTOMERS.IdCustomer%TYPE)
IS BEGIN

  SELECT sqCustomers.NextVal INTO v_IdCustomer FROM DUAL;
  
  INSERT INTO T_CUSTOMERS VALUES (v_IdCustomer, v_FirstName, v_LastName);

END NEW_CUSTOMER;


create or replace
PROCEDURE NEW_PREFERENCE
  (v_IdCLiente IN L_CLIENTES.IdCliente%TYPE, v_DenomInteres IN L_GENEROS.DENOM%TYPE,
   v_TipoAviso IN VARCHAR2)
IS 
  v_IdGenero INTEGER;
BEGIN

  SELECT IDGENERO INTO v_IdGenero 
    FROM L_GENEROS WHERE UPPER(DENOM) = UPPER(v_DenomInteres);

  INSERT INTO L_INFO_NOVEDADES
    VALUES (v_IdCliente, v_IdGenero, v_tipoaviso);
    
  COMMIT;    

END NUEVO_INTERES_CLIENTE;